hibernate:
  properties:
    url: "jdbc:mysql://localhost/szolnok_app?serverTimezone=Europe/Budapest"
    username: "root"
    password: "ENC(c6gkUMdWdiVlteje1bRqCw==)"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    show-sql: "true"
    ddl-auto: "validate"
    dialect: "org.hibernate.dialect.MySQL8Dialect"