info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    kotlin: "@kotlin.version@"
    java: "@java.version@"
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
spring:
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
hibernate:
  properties:
    url: "jdbc:mysql://localhost/szolnok_app?serverTimezone=Europe/Budapest"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    show-sql: "true"
    ddl-auto: "validate"
    dialect: "org.hibernate.dialect.MySQL8Dialect"
timetable:
  resource:
    base-url: "http://archiv.kmkk.hu/"
    szolnok-url: "component/schedule/?city=1"
    selected-buses: []
  selector:
    route-name-selector: "td.route_number"
    from-selector: "table.stations > tbody > tr:nth-child(2) > td:nth-child(3) > a"
    actual-stop-selector: "table.schedule > tbody > tr:nth-child(1) > th > font"
    bus-stops-selector: "table.stations"
    timetable-selector: "table.schedule"
    table-row-selector: "tr"
    table-column-selector: "td"
    routes-link-selector: "td.route_number a"
    href-selector: "href"
    stations-selector: ".stations tr td a"
    other-route-selector: "center > table:nth-child(3) > tbody > tr > td > center > a:nth-child(2)"