server:
  port: ${PORT:8080}
hibernate:
  properties:
    url: "jdbc:mysql://szolnok-app-do-user-3384757-0.db.ondigitalocean.com:25060/szolnok_app?ssl-mode=REQUIRED"
    username: "ENC(yKjCchWtJSlhiQDmy9zKoQ==)"
    password: "ENC(BiHg3OygIdsZL9Jg5AENbgEOraXlzJTK2DXqmaft+Js=)"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    show-sql: "false"
    ddl-auto: "validate"
    dialect: "org.hibernate.dialect.MySQL8Dialect"
admin:
  user:
    username: "ENC(eqCSu76eUpZ3OPu0J8fXDa3tfalh8joMZyxYvPiW1NA=)"
    password: "ENC(0kHSDKSZaLmGpfpuw2nbNOzvnesm2bi3XMZoWyrCBGU=)"