spring:
  h2:
    console:
      enabled: true
      path: "/h2"
hibernate:
  properties:
    url: "jdbc:h2:mem:szolnok_app;INIT=create schema if not exists szolnok_app"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"
    show-sql: "true"
    ddl-auto: "validate"
    dialect: "org.hibernate.dialect.H2Dialect"
admin:
  user:
    username: user
    password: password