hibernate:
  properties:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"
    show-sql: "true"
    ddl-auto: "create-drop"
    dialect: "org.hibernate.dialect.H2Dialect"
admin:
  user:
    username: user
    password: password