info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    kotlin: "@kotlin.version@"
    java: "@java.version@"
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
spring:
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
timetable:
  resource:
    base-url: "http://archiv.kmkk.hu/"
    szolnok-url: "component/schedule/?city=1"
    selected-buses: []
  selector:
    route-name-selector: "td.route_number"
    from-selector: "table.stations > tbody > tr:nth-child(2) > td:nth-child(3) > a"
    actual-stop-selector: "table.schedule > tbody > tr:nth-child(1) > th > font"
    bus-stops-selector: "table.stations"
    timetable-selector: "table.schedule"
    table-row-selector: "tr"
    table-column-selector: "td"
    routes-link-selector: "td.route_number a"
    href-selector: "href"
    stations-selector: ".stations tr td a"
    other-route-selector: "center > table:nth-child(3) > tbody > tr > td > center > a:nth-child(2)"
news:
  resource:
    base-url: "https://www.kmkk.hu/"
  selector:
    news-elements-selector: "div.items-leading article.art-post"
    news-city-selector: "p:nth-child(2) > span:nth-child(1) > span:nth-child(1)"
    news-date-selector: "p:nth-child(2) > span:nth-child(1) > span:nth-child(2)"
    news-title-selector: "div.art-postmetadataheader > h2"
    news-content-selector: "p:nth-child(4) > span"
    news-details-button-selector: "div.art-postcontent.clearfix > p > a.readon.art-button"
    href-selector: "href"
    news-detail-content-selector: "article.art-post hr ~ *"
    allowed-tags:
      - "a"
      - "b"
      - "big"
      - "br"
      - "center"
      - "del"
      - "div"
      - "em"
      - "h1"
      - "h2"
      - "h2"
      - "h3"
      - "h4"
      - "h5"
      - "h6"
      - "i"
      - "li"
      - "ol"
      - "p"
      - "span"
      - "strong"
      - "table"
      - "td"
      - "tr"
      - "title"
      - "ul"
      - "u"