jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}
spring:
  data:
    mongodb:
      host: 217.163.11.185
      port: 27017
      database: pd-db_test
      username: pd-db_test-user
      password: ENC(erzWky5kKS9IJVpqhLa3vN1ZDrCEt0b5ToRGmyI/swY=)
timetable:
  resources:
    locataions:
      # 1 Tallin -> Vegyimuvek
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=1&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=2&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=3&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=4&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=5&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=6&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=7&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=8&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=9&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=10&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=11&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=12&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=13&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=14&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=15&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=16&city=1
      - http://www.kmkk.hu/component/schedule/?route=10101&stage=17&city=1
      # 1 Vegyimuvek -> Tallin
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=1&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=2&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=3&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=4&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=5&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=6&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=7&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=8&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=9&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=10&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=11&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=12&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=13&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=14&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=15&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=16&city=1
      - http://www.kmkk.hu/component/schedule/?route=10102&stage=17&city=1

      # 27 Vasutallomas -> Vasutallomas
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=1&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=2&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=3&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=4&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=5&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=6&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=7&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=8&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=9&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=10&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=11&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=12&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=13&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=14&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=15&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=16&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=17&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=18&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=19&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=20&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=21&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=22&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=23&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=24&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=25&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=26&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=27&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=28&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=29&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=30&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=31&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=32&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=33&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=34&city=1
      - http://www.kmkk.hu/component/schedule/?route=12701&stage=35&city=1

      #24 Vasutallomas -> Vasutallomas
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=1&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=2&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=3&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=4&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=5&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=6&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=7&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=8&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=9&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=10&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=11&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=12&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=13&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=14&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=15&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=16&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=17&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=18&city=1
      - http://www.kmkk.hu/component/schedule/?route=12401&stage=19&city=1