spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
news:
  resource:
    base-url: "https://www.kmkk.hu/"
  selector:
    news-elements-selector: "div.items-leading article.art-post"
    news-city-selector: "p:nth-child(2) > span:nth-child(1) > span:nth-child(1)"
    news-date-selector: "p:nth-child(2) > span:nth-child(1) > span:nth-child(2)"
    news-title-selector: "div.art-postmetadataheader > h2"
    news-content-selector: "p:nth-child(4) > span"
    news-details-button-selector: "div.art-postcontent.clearfix > p > a.readon.art-button"
    href-selector: "href"
    news-detail-content-selector: "article.art-post hr ~ *"
    allowed-tags:
      - "a"
      - "b"
      - "big"
      - "br"
      - "center"
      - "del"
      - "div"
      - "em"
      - "h1"
      - "h2"
      - "h2"
      - "h3"
      - "h4"
      - "h5"
      - "h6"
      - "i"
      - "li"
      - "ol"
      - "p"
      - "span"
      - "strong"
      - "table"
      - "td"
      - "tr"
      - "title"
      - "ul"
      - "u"
